CREATE DATABASE [HierarchyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HierarchyDB', FILENAME = N'C:\Users\lukas\HierarchyDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HierarchyDB_log', FILENAME = N'C:\Users\lukas\HierarchyDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [HierarchyDB] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [HierarchyDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HierarchyDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HierarchyDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HierarchyDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HierarchyDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [HierarchyDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HierarchyDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HierarchyDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [HierarchyDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HierarchyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HierarchyDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HierarchyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HierarchyDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HierarchyDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HierarchyDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HierarchyDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HierarchyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HierarchyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HierarchyDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HierarchyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HierarchyDB] SET  READ_WRITE 
GO
ALTER DATABASE [HierarchyDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HierarchyDB] SET  MULTI_USER 
GO
ALTER DATABASE [HierarchyDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HierarchyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HierarchyDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [HierarchyDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [HierarchyDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [HierarchyDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
